### ISSUE TITLE
requirements.txt file missing

### ISSUE THREAD

**Issue by grcmc** [KarolinaHerlender/pmb#1]
Hi Karolina,
I think good approach will be add requirements.txt file. 
Please execute in WS: pip freeze > requirements.txt
And add this file to repo.

Br,
Michal

**Comment by KarolinaHerlender** [comment]
Please tell me if there are any another troubles with setting up new environment now.

**Comment by grcmc** [comment]
It is still problem with dependency or you commit untested model:

File "/home/michal/pmb/pmb/app/models.py", line 73, in <module>
    class WeekOfMass(models.Model):
  File "/home/michal/pmb/pmb/app/models.py", line 76, in WeekOfMass
    mass_chema = models.ForeignKey(MassSchema, verbose_name='Lista mszy w sezonie')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

Kindly, please check it and fix it.

Br,
Michal

**Comment by KarolinaHerlender** [comment]
I have already fixed it. Sorry for trouble, I forgot to release it. Please check again today evening.

**Comment by KarolinaHerlender** [comment]
Any improvment?
